Transform: AWS::Serverless-2016-10-31
Globals:
    Function:
        Runtime: java11
        MemorySize: 512
Resources:
    AwsDemoUploadsBatchNotifierFunction:
        Type: AWS::Serverless::Function
        Properties:
            PackageType: Zip
            CodeUri: build/distributions/cloudx-aws-lambda-1.0.zip
            FunctionName: aws-demo-uploads-batch-notifier
            Role: arn:aws:iam::748895695737:role/AWSDemoLambdaRole
            Handler: com.example.aws.demo.handler.ImageProcessHandler::handleRequest
            Timeout: 32
